##
post http://localhost:5001/auth/signup
content-type: application/json

{
    "username": "siyabonga",
    "email": "siyabga@example.com",
    "password": "siyabonga@1"
}

##
# get http://localhost:5001/auth/loggin
# content-type: application/json
