# ##
# post http://localhost:5001/auth/loggin
# content-type: application/json

# {
#     "email": "terrance@example.com",
#     "password": "siyabonga@1"
# }

##
post http://localhost:5001/messages/send/7
content-type: application/json

{
    "message": "hey terrance!"
}